INSERT INTO CATEGORY VALUES (1, '남자');
INSERT INTO CATEGORY VALUES (2, '여자');
INSERT INTO CATEGORY VALUES (3, '엑소');
INSERT INTO CATEGORY VALUES (4, '방탄소년단');
INSERT INTO CATEGORY VALUES (5, '블랙핑크');

INSERT INTO CATEGORY VALUES (6, '공지사항');
INSERT INTO CATEGORY VALUES (7, '첸');
INSERT INTO CATEGORY VALUES (8, '백현');
INSERT INTO CATEGORY VALUES (9, '시우민');
INSERT INTO CATEGORY VALUES (10, '공지사항');

INSERT INTO CATEGORY VALUES (11, '익명게시판');
INSERT INTO CATEGORY VALUES (12, '뷔');
INSERT INTO CATEGORY VALUES (13, '공지사항');
INSERT INTO CATEGORY VALUES (14, '로제');

INSERT INTO CATEGORY_RELATIONSHIP VALUES (1, 3, 1);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (2, 4, 1);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (3, 5, 2);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (4, 6, 3);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (5, 7, 3);

INSERT INTO CATEGORY_RELATIONSHIP VALUES (6, 8, 3);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (7, 9, 3);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (8, 10, 4);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (9, 11, 4);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (10, 12, 4);

INSERT INTO CATEGORY_RELATIONSHIP VALUES (11, 13, 5);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (12, 11, 5);
INSERT INTO CATEGORY_RELATIONSHIP VALUES (13, 14, 5);